--# of users where first video watched is by either FEP, live stream, and short film
--first visit field
--average vids watched; d14 d30 retention (ask logic from gabby)


select product, vid_type, series_title, user_profile, count(distinct mpid) as unique_mpids, avg(user_vid_count_by_day) as avg_vids_daily          
    from (select * from (  -- NBC Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from 
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1
       union all
          select * from (  -- BRAVO Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from 
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1 
        union all  
          select * from (  -- E Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1 
        union all 
          select * from (  -- OXYGEN Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1  
        union all  
          select * from (  -- SYFY Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1       
        union all  
          select * from (  -- TELEMUNDO Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1 
        union all  
          select * from (  -- USA Product
            select *, row_number() over (partition by mpid order by event_date asc) as watched_rank, count(*) over (partition by mpid, event_date order by event_date) as user_vid_count_by_day from
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, video_type, show as series_title, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' ) where watched_rank=1   ) group by 1,2,3,4
;



--average vids watched; d14 d30 retention (ask logic from gabby)
--check linear duration greater than 0




        select * from   -- NBC Product
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019'
       union all
          select * from   -- BRAVO Product
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."BRAVO_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019'
        union all  
          select * from   -- E Product
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."E_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019'
        union all 
          select * from   -- OXYGEN Product
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."OXYGEN_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019'
        union all  
          select * from   -- SYFY Product
              (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."SYFY_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019'     
        union all  
          select * from   -- TELEMUNDO Product
            (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
//            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
//              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."TELEMUNDO_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' 
        union all  
          select * from   -- USA Product
            (select '201912' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201912" where event_name_lowercase in ('video start', 'linear start')
            union all select '201911' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201911" where event_name_lowercase in ('video start', 'linear start')
            union all select '201910' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201910" where event_name_lowercase in ('video start', 'linear start')
            union all select '201909' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201909" where event_name_lowercase in ('video start', 'linear start')
            union all select '201908' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201908" where event_name_lowercase in ('video start', 'linear start')
            union all select '201907' as month, mparticle_id as mpid, cast(event_date_pst_nbcent_calc as date) as event_date, event_name as en, upper(events_product) as product, brand, user_profile, user_sign_in_type, user_first_visit_date
              , case when (event_name_lowercase = 'linear start' or video_type='linear start') then 'Live Stream' when video_type='Full Episode' then 'FEP' else 'Short Film' end as vid_type from "WALDO_PROD"."MPARTICLE"."USA_CUSTOM_EVENT_201907" where event_name_lowercase in ('video start', 'linear start')
            ) where month(user_first_visit_date) in ('7','8','9','10','11') and year(user_first_visit_date)='2019' 
;



        
        
        